# Överstyr tjänster som byggs lokalt för att i stället använda bilder
# som publiceras via GitHub Actions.
services:
  app:
    image: ${GHCR_APP_IMAGE:?Sätt GHCR_APP_IMAGE i .env}
    build: null

  app_demo:
    image: ${GHCR_APP_DEMO_IMAGE:?Sätt GHCR_APP_DEMO_IMAGE i .env}
    build: null

  status_page:
    image: ${GHCR_STATUS_PAGE_IMAGE:?Sätt GHCR_STATUS_PAGE_IMAGE i .env}
    build: null

  antivirus:
    image: ${GHCR_ANTIVIRUS_IMAGE:?Sätt GHCR_ANTIVIRUS_IMAGE i .env}
    build: null
