name: Snyk Security

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk:
    permissions:
      contents: read                # för actions/checkout
      security-events: write        # för upload-sarif
      actions: read                 # behövs för privata repo ibland
    runs-on: ubuntu-latest

    env:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SNYK_ORG: mr-cool08           # byt om din org-slug är annan
      SNYK_REGION: eu
      SNYK_API: https://api.eu.snyk.io

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Snyk CLI
        uses: snyk/actions/setup@806182742461562b67788a64410098c9d9b96adb

      # Snyk Code (SAST)
      - name: Snyk Code test
        run: snyk code test --sarif -d > snyk-code.sarif
        continue-on-error: true

      # Snyk Open Source (SCA)
      - name: Snyk Open Source monitor
        run: snyk monitor --all-projects
        continue-on-error: true

      # Snyk IaC
      - name: Snyk IaC test and report
        run: snyk iac test --report
        continue-on-error: true

      # Bygg Docker-image för container-scan
      - name: Build a Docker image
        run: docker build -t your/image-to-test .

      # Snyk Container
      - name: Snyk Container monitor
        run: snyk container monitor your/image-to-test --file=Dockerfile
        continue-on-error: true

      # Ladda upp SARIF till GitHub Code Scanning
      - name: Upload result to GitHub Code Scanning
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk-code.sarif
